name: Release docker image

on:
  workflow_dispatch: {}
  release:
    types: [published]


permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # Build docker images
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: {% raw %}${{ vars.DOCKERHUB_USERNAME }}{% endraw %}
        password: {% raw %}${{ secrets.DOCKERHUB_TOKEN }}{% endraw %}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: {{ cookiecutter.github_username }}
        password: {% raw %}${{ secrets.PAT }}{% endraw %}
    -
      name: Build and push image
      id: docker_build_publish
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64/v8
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: ./docker/Dockerfile
        push: true
        tags: |
          {% raw %}${{ vars.DOCKERHUB_USERNAME }}{% endraw %}/{{ cookiecutter.project_name }}:latest
          ghcr.io/{{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}:latest
          {% raw %}${{ vars.DOCKERHUB_USERNAME }}{% endraw %}/{{ cookiecutter.project_name }}:{% raw %}${{ github.ref_name }}{% endraw %}
          ghcr.io/{{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}:{% raw %}${{ github.ref_name }}{% endraw %}
