name: Testing docker image build

on:
  pull_request:
    branches: [ "master", "main" ]

jobs:
  deploy:
    strategy:
        fail-fast: true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      # Self versioning
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine hatch
    - name: Versioning package
      run: hatch version {% raw %}${{ github.ref_name }}{% endraw %}
    # Build docker images
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push release
      id: docker_build_release
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        file: ./docker/Dockerfile
        push: false
        tags: {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}/{{ cookiecutter.project_name }}:latest
