name: Testing docker image build

on:
  pull_request:
    branches: [ "master", "main" ]

jobs:
  deploy:
    strategy:
        fail-fast: true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Build docker images
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}
        password: {% raw %}${{ secrets.DOCKERHUB_TOKEN }}{% endraw %}
    -
      name: Build and push release
      id: docker_build_release
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: ./docker/Dockerfile
        push: false
        tags: {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}/{{ cookiecutter.project_name }}:latest
