name: Release docker image

on:
  workflow_dispatch: {}
  release:
    types: [published]


permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # Build docker images
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}
        password: {% raw %}${{ secrets.DOCKERHUB_TOKEN }}{% endraw %}
    -
      name: Build and push image
      id: docker_build_publish
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: ./docker/Dockerfile
        push: true
        tags: {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}/{{ cookiecutter.project_name }}:{% raw %}${{ github.ref_name }}{% endraw %}
